const char* indexHtml = 
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
   "<input type='file' name='update'>"
        "<input type='submit' value='Update'>"
    "</form>"
 "<div id='prg'>progress: 0%</div>"
 "<script>"
  "$('form').submit(function(e){"
  "e.preventDefault();"
  "var form = $('#upload_form')[0];"
  "var data = new FormData(form);"
  " $.ajax({"
  "url: '/update',"
  "type: 'POST',"
  "data: data,"
  "contentType: false,"
  "processData:false,"
  "xhr: function() {"
  "var xhr = new window.XMLHttpRequest();"
  "xhr.upload.addEventListener('progress', function(evt) {"
  "if (evt.lengthComputable) {"
  "var per = evt.loaded / evt.total;"
  "$('#prg').html('progress: ' + Math.round(per*100) + '%');"
  "}"
  "}, false);"
  "return xhr;"
  "},"
  "success:function(d, s) {"
  "console.log('success!')" 
 "},"
 "error: function (a, b, c) {"
 "}"
 "});"
 "});"
 "</script>";
const char* otaHtml = 
"<!DOCTYPE html>\n"
"<html>\n"
"  <head> </head>\n"
"  <body>\n"
"    <form\n"
"      method='POST'\n"
"      action='#'\n"
"      enctype='multipart/form-data'\n"
"      id='upload_form'\n"
"    >\n"
"      <input type='file' name='update' />\n"
"      <input type='submit' value='Update' />\n"
"    </form>\n"
"    <div id='prg'>progress: 0%</div>\n"
"    <script>\n"
"      const form = document.getElementById('upload_form');\n"
"      form.addEventListener('submit', (e) => {\n"
"        e.preventDefault();\n"
"        const data = new FormData(form);\n"
"        console.log(data);\n"
"        console.log(\n"
"          'Created FormData, ' + [...data.keys()].length + ' keys in data'\n"
"        );\n"
"\n"
"        var xhr = new XMLHttpRequest();\n"
"        xhr.onreadystatechange = function () {\n"
"          if (xhr.readyState == XMLHttpRequest.DONE) {\n"
"            // XMLHttpRequest.DONE == 4\n"
"            if (xhr.status == 200) {\n"
"              document.getElementById('myDiv').innerHTML = xhr.responseText;\n"
"            } else if (xhr.status == 400) {\n"
"              alert('There was an error 400');\n"
"            } else {\n"
"              alert('something else other than 200 was returned');\n"
"            }\n"
"          }\n"
"        };\n"
"        xhr.upload.addEventListener(\n"
"          'progress',\n"
"          function (evt) {\n"
"            if (evt.lengthComputable) {\n"
"              var per = evt.loaded / evt.total;\n"
"              document.getElementById('prg').innerHTML =\n"
"                'progress: ' + Math.round(per * 100) + '%';\n"
"            }\n"
"          },\n"
"          false\n"
"        );\n"
"        xhr.open('POST', '/update');\n"
"        console.log(xhr);\n"
"        xhr.send(data);\n"
"      });\n"
"    </script>\n"
"  </body>\n"
"</html>\n";
 const char* aboutHtml = "EMPTY";
