const char* indexHtml = 
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
   "<input type='file' name='update'>"
        "<input type='submit' value='Update'>"
    "</form>"
 "<div id='prg'>progress: 0%</div>"
 "<script>"
  "$('form').submit(function(e){"
  "e.preventDefault();"
  "var form = $('#upload_form')[0];"
  "var data = new FormData(form);"
  " $.ajax({"
  "url: '/update',"
  "type: 'POST',"
  "data: data,"
  "contentType: false,"
  "processData:false,"
  "xhr: function() {"
  "var xhr = new window.XMLHttpRequest();"
  "xhr.upload.addEventListener('progress', function(evt) {"
  "if (evt.lengthComputable) {"
  "var per = evt.loaded / evt.total;"
  "$('#prg').html('progress: ' + Math.round(per*100) + '%');"
  "}"
  "}, false);"
  "return xhr;"
  "},"
  "success:function(d, s) {"
  "console.log('success!')" 
 "},"
 "error: function (a, b, c) {"
 "}"
 "});"
 "});"
 "</script>";
const char* otaHtml = 
"<!DOCTYPE html>"
"<html>"
"  <head>"
"    <meta http-equiv='content-type' content='text/html; charset=utf-8' />"
"    <title>ESP32 OTA Update</title>"
"  </head>"
"  <body>"
"    <h1>ESP32 OTA Firmware Update</h1>"
"    <div>"
"      <label for='otafile'>Firmware file:</label>"
"      <input type='file' id='otafile' name='otafile' />"
"    </div>"
"    <div>"
"      <button id='upload' type='button' onclick='startUpload()'>Upload</button>"
"    </div>"
"    <div id='progress'></div>"
"    <script>"
"      function startUpload() {"
"        var otafile = document.getElementById('otafile').files;"
"        if (otafile.length == 0) {"
"          alert('No file selected!');"
"        } else {"
"          document.getElementById('otafile').disabled = true;"
"          document.getElementById('upload').disabled = true;"
"          var file = otafile[0];"
"          var xhr = new XMLHttpRequest();"
"          xhr.onreadystatechange = function () {"
"            if (xhr.readyState == 4) {"
"              if (xhr.status == 200) {"
"                document.open();"
"                document.write(xhr.responseText);"
"                document.close();"
"              } else if (xhr.status == 0) {"
"                alert('Server closed the connection abruptly!');"
"                location.reload();"
"              } else {"
"                alert(xhr.status + ' Error! ' + xhr.responseText);"
"                location.reload();"
"              }"
"            }"
"          };"
"          xhr.upload.onprogress = function (e) {"
"            var progress = document.getElementById('progress');"
"            progress.textContent ="
"              'Progress: ' + ((e.loaded / e.total) * 100).toFixed(0) + '%';"
"          };"
"          xhr.open('POST', '/update', true);"
"          xhr.send(file);"
"        }"
"      }"
"    </script>"
"  </body>"
"</html>";
 const char* aboutHtml = "Code compile stamp: 122923";
