const char* otaFetchHtml = 
"<!DOCTYPE html>"
"<html>"
"  <head> </head>"
"  <body>"
"    <form"
"      method='POST'"
"      action='#'"
"      enctype='multipart/form-data'"
"      id='upload_form'"
"      onsubmit='handleSubmit()'"
"    >"
"      <input type='file' name='update' />"
"      <input type='submit' value='Update' />"
"    </form>"
"    <script>"
"      function handleSubmit(e) {"
"        e.preventDefault();"
"        const form = document.getElementById('upload_form')[0];"
"        const data = new FormData(form);"
"        const url = new URL('/update');"
"        const options = {"
"          method: form.method,"
"          body: data,"
"        };"
"        fetch(url, options);"
"      }"
"    </script>"
"  </body>"
"</html>";